AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating a free tier eligible EC2 instance with two security groups'

Parameters:
  AdminIpRange:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    Default: 203.0.113.0/24 #replace `203.0.113.0/24` with the IP range you want to allow SSH access from. The default value is an RFC 5735 address, failing to update it will leave your EC2 instance inaccessible.
    
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0aa7d40eeae50c9a9  # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
    us-east-2:
      AMI: ami-0a695f0d95cefc163  # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type


Resources:
  HoneypotKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: honeypot-key-pair

  HoneypotInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      # The ImageId is dynamically selected based on the current AWS region
      # using the RegionMap defined in the Mappings section.
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      KeyName: !Ref HoneypotKeyPair
      SecurityGroups:
        - !Ref AdminSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 8
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: DShield-Instance

  AdminSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22 # once the honeypot has been installed on this instance, the security group will need to be manually updated to port 12222
        ToPort: 22
        CidrIp: !Ref AdminIpRange

  UnrestrictedSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow unrestricted access
      SecurityGroupIngress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref HoneypotInstance
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt HoneypotInstance.PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt HoneypotInstance.PublicIp
  KeyPairName:
    Description: Name of the created EC2 Key Pair
    Value: !Ref HoneypotKeyPair
  KeyPairFingerprint:
    Description: Fingerprint of the created EC2 Key Pair
    Value: !GetAtt HoneypotKeyPair.KeyFingerprint